name: Crossplatform CI

on:
  push:
    paths:
      - 'src/**'
      - 'contrib/**'
      - 'CMakeLists.txt'
  pull_request:
    paths:
      - 'src/**'
      - 'contrib/**'
      - 'CMakeLists.txt'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      env:
        VERBOSE: 1
