name: Linter

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: curl -o cpplint.py https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py

    - name: Lint
      run: |
        python2 cpplint.py \
          --linelength=90 \
          --filter=-build/header_guard,-build/include,-build/c++11 \
          src/* \
          src/blueprints/* \
          src/core/* \
          src/objects/* \
          src/plugins/* \
          src/strategies/* \
          src/strategies/protoss/* \
          src/strategies/terran/* \
          src/strategies/zerg/*
